// 2026-09-21: 사용자가 올린 세 장의 필기 사진에서 확인한 단어 모음입니다.
// 화면/저장 로직과 분리해 두어 이후 사진 인식 기능을 붙일 때 교체하기 쉽습니다.
export const handwrittenWordTemplates = [
  { id: "notes-occupant", word: "occupant", meanings: ["거주자", "점유자"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-occupancy", word: "occupancy", meanings: ["거주", "점유", "입주"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-completion", word: "completion", meanings: ["완성", "완료"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-relocate", word: "relocate", meanings: ["이동하다", "이전하다", "이주하다", "재배치하다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-lead", word: "lead", meanings: ["이끌다", "초래하다"], partOfSpeech: "동사", memo: "불규칙 변화: lead-led-led", tags: ["필기"] },
  { id: "notes-lead-to", word: "lead to", meanings: ["~로 이어지다", "~을 초래하다"], partOfSpeech: "숙어", memo: "", tags: ["필기"] },
  { id: "notes-considerable", word: "considerable", meanings: ["상당한", "꽤 많은"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-enhancement", word: "enhancement", meanings: ["개선", "향상"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-intuitive", word: "intuitive", meanings: ["직관적인"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-previous", word: "previous", meanings: ["이전의"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-organic", word: "organic", meanings: ["유기농의", "유기적인"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-produce", word: "produce", meanings: ["생산물", "농산물", "생산하다", "만들어 내다"], partOfSpeech: "명사·동사", memo: "명사일 때는 첫 음절, 동사일 때는 둘째 음절에 강세", tags: ["필기"] },
  { id: "notes-decade", word: "decade", meanings: ["10년"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-finance", word: "finance", meanings: ["재정", "금융", "자금", "자금을 조달하다"], partOfSpeech: "명사·동사", memo: "", tags: ["필기"] },
  { id: "notes-financial", word: "financial", meanings: ["재정의", "금융의"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-finance-director", word: "finance director", meanings: ["재무 담당 이사"], partOfSpeech: "복합 명사", memo: "", tags: ["필기"] },
  { id: "notes-reallocate", word: "reallocate", meanings: ["재분배하다", "재할당하다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-fund", word: "fund", meanings: ["자금", "기금", "자금을 지원하다"], partOfSpeech: "명사·동사", memo: "", tags: ["필기"] },
  { id: "notes-unexpected", word: "unexpected", meanings: ["예기치 않은", "예상 밖의"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-budget", word: "budget", meanings: ["예산"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-budget-cuts", word: "budget cuts", meanings: ["예산 삭감", "예산 축소"], partOfSpeech: "복합 명사", memo: "필기의 'budget gets'를 문맥에 맞는 budget cuts로 판독·보정", tags: ["필기"] },
  { id: "notes-client", word: "client", meanings: ["고객", "의뢰인"], partOfSpeech: "명사", memo: "", tags: ["필기"] },

  { id: "notes-essential", word: "essential", meanings: ["필수적인"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-aim", word: "aim", meanings: ["목표", "목표로 하다"], partOfSpeech: "명사·동사", memo: "aim at + 명사: ~을 목표로 하다 / aim to + 동사원형: ~하는 것을 목표로 하다", tags: ["필기"] },
  { id: "notes-crop", word: "crop", meanings: ["작물"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-irrigate", word: "irrigate", meanings: ["관개하다"], partOfSpeech: "동사", memo: "농작물이 자라도록 물을 끌어오는 행위", tags: ["필기"] },
  { id: "notes-dependence", word: "dependence", meanings: ["의존"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-foreign", word: "foreign", meanings: ["외국의"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-lower", word: "lower", meanings: ["낮추다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-ease", word: "ease", meanings: ["편안함", "완화되다", "완화하다"], partOfSpeech: "명사·동사", memo: "", tags: ["필기"] },
  { id: "notes-workload", word: "workload", meanings: ["업무량"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-shortcut", word: "shortcut", meanings: ["단축키", "지름길", "손쉬운 방법"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-automate", word: "automate", meanings: ["자동화하다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-repetitive", word: "repetitive", meanings: ["반복적인", "반복되는"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-task", word: "task", meanings: ["일", "업무"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-responsibility", word: "responsibility", meanings: ["책임"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-among-other-things", word: "among other things", meanings: ["그중에서도", "여러 가지 중에서도", "그 밖에도"], partOfSpeech: "관용 표현", memo: "여러 사항 중 하나를 언급할 때 사용. '무엇보다도'라는 우선순위의 뜻은 above all과 구별", tags: ["필기"] },
  { id: "notes-address", word: "address", meanings: ["다루다", "처리하다", "연설하다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-concern", word: "concern", meanings: ["걱정", "염려", "관심사"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-ensure", word: "ensure", meanings: ["보장하다", "확실하게 하다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-inspect", word: "inspect", meanings: ["검사하다", "점검하다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-despite", word: "despite", meanings: ["~에도 불구하고"], partOfSpeech: "전치사", memo: "", tags: ["필기"] },
  { id: "notes-tough", word: "tough", meanings: ["힘든", "어려운"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-state", word: "state", meanings: ["상태", "주", "국가", "말하다", "언급하다"], partOfSpeech: "명사·동사", memo: "", tags: ["필기"] },
  { id: "notes-remain", word: "remain", meanings: ["남아 있다", "계속 ~이다"], partOfSpeech: "동사", memo: "자동사 또는 연결동사로 쓰임", tags: ["필기"] },
  { id: "notes-sound", word: "sound", meanings: ["소리", "건실한", "이상 없는", "소리가 나다", "~을 울리다"], partOfSpeech: "명사·형용사·동사", memo: "여러 품사로 쓰이는 단어", tags: ["필기"] },
  { id: "notes-diverse", word: "diverse", meanings: ["다양한"], partOfSpeech: "형용사", memo: "", tags: ["필기"] },
  { id: "notes-revenue", word: "revenue", meanings: ["수입", "매출"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-stream", word: "stream", meanings: ["흐름", "지속적인 공급원"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-revenue-stream", word: "revenue stream", meanings: ["수입원", "매출원"], partOfSpeech: "복합 명사", memo: "revenue + stream으로 이루어진 복합 명사", tags: ["필기"] },
  { id: "notes-specialized", word: "specialized", meanings: ["전문화된", "전문적인"], partOfSpeech: "형용사", memo: "specialize의 분사형이지만 형용사로도 굳어져 쓰임", tags: ["필기"] },

  { id: "notes-small-and-medium-enterprise", word: "small and medium enterprise", meanings: ["중소기업"], partOfSpeech: "복합 명사", memo: "", tags: ["필기"] },
  { id: "notes-implement", word: "implement", meanings: ["시행하다", "실행하다", "구현하다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-now-that", word: "now that", meanings: ["이제 ~이므로"], partOfSpeech: "접속사", memo: "", tags: ["필기"] },
  { id: "notes-demand", word: "demand", meanings: ["수요", "요구"], partOfSpeech: "명사", memo: "", tags: ["필기"] },
  { id: "notes-significantly", word: "significantly", meanings: ["상당히", "현저하게"], partOfSpeech: "부사", memo: "", tags: ["필기"] },
  { id: "notes-no-longer", word: "no longer", meanings: ["더 이상 ~않다", "더 이상 ~하지 않다"], partOfSpeech: "부사구", memo: "", tags: ["필기"] },
  { id: "notes-commercial", word: "commercial", meanings: ["광고", "상업의", "상업적인"], partOfSpeech: "명사·형용사", memo: "", tags: ["필기"] },
  { id: "notes-catch", word: "catch", meanings: ["잡다", "이해하다"], partOfSpeech: "동사", memo: "", tags: ["필기"] },
  { id: "notes-detail", word: "detail", meanings: ["세부 사항", "상세히 설명하다"], partOfSpeech: "명사·동사", memo: "", tags: ["필기"] },
  { id: "notes-conference-call", word: "conference call", meanings: ["원격 회의", "전화 회의"], partOfSpeech: "복합 명사", memo: "", tags: ["필기"] }
];
